In [1]:
import statistics as st


In [2]:
a= [10,20,50,10,21,90]

In [3]:
mn = st.mean(a)
print("mean:",mn)

mean: 33.5


In [4]:
md = st.mode(a)
print("Mode:",md)

Mode: 10


In [5]:
mdn = st.median(a)
print("Median",mdn)

Median 20.5


In [6]:
import numpy as np

In [7]:
b = np.array([[10,20,30,50,10],[1,2,3,5,6]])
print(b)
print(b.ndim)

[[10 20 30 50 10]
 [ 1  2  3  5  6]]
2


In [8]:
b = np.array([[10,20,30,50,10],[1,2,3,5,6],[1,1,1,1,1]])
print(b)

[[10 20 30 50 10]
 [ 1  2  3  5  6]
 [ 1  1  1  1  1]]


In [9]:
print("Dim:",b.ndim)
print("Shape:",b.shape)

Dim: 2
Shape: (3, 5)


In [10]:
print("Size:",b.size)
print("Item Size:",b.itemsize)
print("Data type:",b.dtype)

Size: 15
Item Size: 8
Data type: int64


In [11]:
c = np.empty((5,5))
print(c)

[[4.18185813e-315 0.00000000e+000 8.25089629e-322             nan
  1.27701034e+232]
 [4.63362087e+228 1.94670827e+227 2.64521300e+185 1.28824057e+214
  3.52531059e+246]
 [6.01099947e+175 2.32161870e-152 2.35903094e+251 1.32756640e-258
  5.60481379e+199]
 [1.44427036e+214 9.70598276e+189 9.06691964e+271 7.35423712e+223
  1.67792002e+243]
 [1.14735323e+253 1.41592481e+190 3.06225710e+169 1.29152844e+161
  1.44577178e-308]]


In [12]:
g = np.full((3,3),5)
print(g)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [13]:
d = np.arange(0,100,2)
print(d)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [14]:
e = np.reshape(d,(10,5))
print(e)

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]
 [60 62 64 66 68]
 [70 72 74 76 78]
 [80 82 84 86 88]
 [90 92 94 96 98]]


In [15]:
f = np.reshape(e,(2,5,5))
print(f)

[[[ 0  2  4  6  8]
  [10 12 14 16 18]
  [20 22 24 26 28]
  [30 32 34 36 38]
  [40 42 44 46 48]]

 [[50 52 54 56 58]
  [60 62 64 66 68]
  [70 72 74 76 78]
  [80 82 84 86 88]
  [90 92 94 96 98]]]


In [16]:
print("Dim:",f.ndim)

Dim: 3


In [17]:
print("Elements upto 10:",d[:10])
print("Last 10 Elements:",d[-10:])
print("Alternative Numbers:",d[::2])


Elements upto 10: [ 0  2  4  6  8 10 12 14 16 18]
Last 10 Elements: [80 82 84 86 88 90 92 94 96 98]
Alternative Numbers: [ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92
 96]


In [18]:
import pandas as pd

In [19]:
p_dict = {'pid': [1,2,3,4,5],
          'value': [10,20,30,40,50],
          'vendor': ['V1','V2','V3','V4','V5']}

In [20]:
print(p_dict)
df = pd.DataFrame(p_dict)
df

{'pid': [1, 2, 3, 4, 5], 'value': [10, 20, 30, 40, 50], 'vendor': ['V1', 'V2', 'V3', 'V4', 'V5']}


,pid,value,vendor
0,1,10,V1
1,2,20,V2
2,3,30,V3
3,4,40,V4
4,5,50,V5
