In [3]:
import statistics as st

In [4]:
a= [10,20,50,10,21,90]

In [5]:
mn = st.mean(a)
print("mean:",mn)

mean: 33.5


In [6]:
md = st.mode(a)
print("Mode:",md)

Mode: 10


In [7]:
mdn = st.median(a)
print("Median",mdn)

Median 20.5


In [8]:
import numpy as np

In [9]:
b = np.array([[10,20,30,50,10],[1,2,3,5,6]])
print(b)
print(b.ndim)

[[10 20 30 50 10]
 [ 1  2  3  5  6]]
2


In [10]:
b = np.array([[10,20,30,50,10],[1,2,3,5,6],[1,1,1,1,1]])
print(b)

[[10 20 30 50 10]
 [ 1  2  3  5  6]
 [ 1  1  1  1  1]]


In [11]:
print("Dim:",b.ndim)
print("Shape:",b.shape)

Dim: 2
Shape: (3, 5)


In [12]:
print("Size:",b.size)
print("Item Size:",b.itemsize)
print("Data type:",b.dtype)

Size: 15
Item Size: 8
Data type: int64


In [13]:
c = np.empty((5,5))
print(c)

[[4.37042071e-315 0.00000000e+000 5.75761574e-317 6.93553838e-310
  6.93553838e-310]
 [6.93553838e-310 5.75761574e-317 6.93552868e-310 6.93552868e-310
  6.93554220e-310]
 [4.26597679e-096 5.58294180e-322 4.35779615e-315 6.93554365e-310
  3.37423605e-057]
 [1.04917185e-153 9.08366791e+223 6.14415221e-144 5.34855557e-317
  2.42092166e-322]
 [4.36489994e-315 6.93554365e-310 4.25831876e-315 4.25831876e-315
  4.18967668e-321]]


In [14]:
g = np.full((3,3),5)
print(g)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [15]:
d = np.arange(0,100,2)
print(d)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [16]:
e = np.reshape(d,(10,5))
print(e)

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]
 [60 62 64 66 68]
 [70 72 74 76 78]
 [80 82 84 86 88]
 [90 92 94 96 98]]


In [17]:
f = np.reshape(e,(2,5,5))
print(f)

[[[ 0  2  4  6  8]
  [10 12 14 16 18]
  [20 22 24 26 28]
  [30 32 34 36 38]
  [40 42 44 46 48]]

 [[50 52 54 56 58]
  [60 62 64 66 68]
  [70 72 74 76 78]
  [80 82 84 86 88]
  [90 92 94 96 98]]]


In [18]:
print("Dim:",f.ndim)

Dim: 3


In [19]:
print("Elements upto 10:",d[:10])
print("Last 10 Elements:",d[-10:])
print("Alternative Numbers:",d[::2])


Elements upto 10: [ 0  2  4  6  8 10 12 14 16 18]
Last 10 Elements: [80 82 84 86 88 90 92 94 96 98]
Alternative Numbers: [ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92
 96]


In [20]:
import pandas as pd

In [21]:
p_dict = {'pid': [1,2,3,4,5],
          'value': [10,20,30,40,50],
          'vendor': ['V1','V2','V3','V4','V5']}

In [22]:
print(p_dict)
df = pd.DataFrame(p_dict)
df

{'pid': [1, 2, 3, 4, 5], 'value': [10, 20, 30, 40, 50], 'vendor': ['V1', 'V2', 'V3', 'V4', 'V5']}


,pid,value,vendor
0,1,10,V1
1,2,20,V2
2,3,30,V3
3,4,40,V4
4,5,50,V5
