In [3]:
import statistics as st

In [4]:
a= [10,20,50,10,21,90]

In [5]:
mn = st.mean(a)
print("mean:",mn)

mean: 33.5


In [6]:
md = st.mode(a)
print("Mode:",md)

Mode: 10


In [7]:
mdn = st.median(a)
print("Median",mdn)

Median 20.5


In [8]:
import numpy as np

In [9]:
b = np.array([[10,20,30,50,10],[1,2,3,5,6]])
print(b)
print(b.ndim)

[[10 20 30 50 10]
 [ 1  2  3  5  6]]
2


In [10]:
b = np.array([[10,20,30,50,10],[1,2,3,5,6],[1,1,1,1,1]])
print(b)

[[10 20 30 50 10]
 [ 1  2  3  5  6]
 [ 1  1  1  1  1]]


In [11]:
print("Dim:",b.ndim)
print("Shape:",b.shape)

Dim: 2
Shape: (3, 5)


In [12]:
print("Size:",b.size)
print("Item Size:",b.itemsize)
print("Data type:",b.dtype)

Size: 15
Item Size: 8
Data type: int64


In [13]:
c = np.empty((5,5))
print(c)

[[6.23042070e-307 4.89547485e-307 7.56604561e-307 1.78017181e-306
  6.23058368e-307]
 [3.11526468e-307 3.22651328e-307 1.33509117e-306 1.11258854e-306
  1.11261502e-306]
 [1.42410839e-306 7.56597770e-307 6.23059726e-307 1.42419530e-306
  1.11261027e-306]
 [6.89805151e-307 7.56592338e-307 6.89807188e-307 1.11261095e-306
  1.69120552e-306]
 [2.22522597e-306 1.33511969e-306 1.05695167e-307 8.45610231e-307
  3.20552953e-317]]


In [14]:
g = np.full((3,3),5)
print(g)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [15]:
d = np.arange(0,100,2)
print(d)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [16]:
e = np.reshape(d,(10,5))
print(e)

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]
 [60 62 64 66 68]
 [70 72 74 76 78]
 [80 82 84 86 88]
 [90 92 94 96 98]]


In [17]:
f = np.reshape(e,(2,5,5))
print(f)

[[[ 0  2  4  6  8]
  [10 12 14 16 18]
  [20 22 24 26 28]
  [30 32 34 36 38]
  [40 42 44 46 48]]

 [[50 52 54 56 58]
  [60 62 64 66 68]
  [70 72 74 76 78]
  [80 82 84 86 88]
  [90 92 94 96 98]]]


In [18]:
print("Dim:",f.ndim)

Dim: 3


In [19]:
print("Elements upto 10:",d[:10])
print("Last 10 Elements:",d[-10:])
print("Alternative Numbers:",d[::2])


Elements upto 10: [ 0  2  4  6  8 10 12 14 16 18]
Last 10 Elements: [80 82 84 86 88 90 92 94 96 98]
Alternative Numbers: [ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92
 96]


In [20]:
import pandas as pd

In [21]:
p_dict = {'pid': [1,2,3,4,5],
          'value': [10,20,30,40,50],
          'vendor': ['V1','V2','V3','V4','V5']}

In [22]:
print(p_dict)
df = pd.DataFrame(p_dict)
df

{'pid': [1, 2, 3, 4, 5], 'value': [10, 20, 30, 40, 50], 'vendor': ['V1', 'V2', 'V3', 'V4', 'V5']}


pid  value vendor
0    1     10     V1
1    2     20     V2
2    3     30     V3
3    4     40     V4
4    5     50     V5